server:
  port: 9000
spring:
  application:
    name: authorization-server
  h2:
    console:
      enabled: true
  freemarker:
    suffix: .html


logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.jdbc.datasource.embedded: info