server:
  port: 9000
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
spring:
  application:
    name: authorization-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:authorization-server;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console
  freemarker:
    template-loader-path: classpath:/site/
    suffix: .html
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 2592000
          no-transform: true
      chain:
        compressed: true


logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.jdbc.datasource.embedded: info
    org.springframework.security.oauth2.server.authorization.web.OAuth2AuthorizationEndpointFilter: trace