server:
  port: 9001

spring:
  security:
    oauth2:
      client:
        registration:
          iam:
            provider: iam
            client-id: test-client
            client-secret: secret
            redirect-uri: http://127.0.0.1:9001/login/oauth2/code/iam
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: message.read,message.write,openid
          iam-oidc:
            provider: iam
            client-id: test-client
            client-secret: secret
            redirect-uri: http://127.0.0.1:9001/login/oauth2/code/iam-oidc
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          iam:
            #  provider 尽量用域名  不要用localhost或者IP  而且要和well-known接口中保持一致; 不要与 Client 配置成为统一域名
            issuer-uri: http://192.168.2.5:9000
            # issuer-uri 可以简化下面的配置
            # authorization-uri: http://localhost:9000/oauth2/authorize
            # token-uri: http://localhost:9000/oauth2/token
            # user-info-uri: http://your-userinfo-endpoiont
            # user-name-attribute: username
            # user-info-authentication-method: GET

sso:
  web:
    enable: true

# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    io.github.code13.spring.security.oauth2.client.sso.OAuth2SsoCondition: trace